/**
 * The phrase deck. Data only — no logic lives here.
 * Constraints enforced by bingo.test.js: unique, trimmed, non-empty,
 * at most 40 characters so a phrase still fits a 4x4 cell on a phone.
 */
export const DECK = [
  "Let's circle back",
  'Low-hanging fruit',
  'Move the needle',
  'Synergy',
  'Boil the ocean',
  'Take this offline',
  'At the end of the day',
  'Double-click on that',
  'Ping me',
  'Touch base',
  'Deep dive',
  'Drill down',
  'Bandwidth',
  'Peel the onion',
  'Boots on the ground',
  'Run it up the flagpole',
  'Park that for now',
  'Table stakes',
  'Best practice',
  'Paradigm shift',
  'Think outside the box',
  'Push the envelope',
  'Level set',
  'Socialize the idea',
  'On the same page',
  'Close the loop',
  'Loop me in',
  'Action items',
  'Actionable insights',
  'Key takeaways',
  'Quick win',
  'Value add',
  'Win-win',
  'Core competency',
  'Secret sauce',
  'Game changer',
  'Disruptive',
  'Holistic approach',
  'End-to-end',
  '360-degree view',
  'Helicopter view',
  'Big picture',
  'Granular',
  'Bleeding edge',
  'Best-of-breed',
  'Turnkey solution',
  'Scalable',
  'Future-proof',
  'Mission critical',
  'High-level',
  'Subject matter expert',
  'Stakeholder buy-in',
  'Sign-off',
  'Cross-functional',
  'Break down silos',
  'Dotted line',
  'Escalate',
  'All hands on deck',
  'Backlog grooming',
  'Story points',
  'Velocity',
  'Definition of done',
  'Blocker',
  'Parking lot',
  'MVP',
  'North star',
  'OKRs',
  'KPI',
  'Data-driven decision',
  'Single source of truth',
  'Guardrails',
  'Roadmap',
  'Headwinds',
  'Sunset that',
  'Do more with less',
  'Wear many hats',
  'Rockstar',
  'Culture fit',
  'The journey, not the destination',
  'Learnings',
  'Operationalize',
  'Bring to the table',
  'Streamline',
  'Optimize',
  'Fail fast',
  'Pivot',
  'Lean in',
  'Take ownership',
  'Empower the team',
  'Customer-centric',
  'Voice of the customer',
  'Value proposition',
  'Technical debt',
  'Unpack that',
  'Elephant in the room',
  'Swim lane',
  'Eat our own dog food',
  'Above my pay grade',
  "Let's take a step back",
  'Hard stop',
  "You're on mute",
  'Can everyone see my screen?',
  'This could have been an email',
  'Per my last email',
  "Let's find time",
  "I'll send an invite",
  'Keep me posted',
  'Circling back on this',
];
